name: Build LaTeX document and push the compiled PDF back to GitHub
on:
  push:
    paths:
      - '**.tex'
      - '**.cls'
jobs:
  build_latex:
    runs-on: ubuntu-latest
    env:
      MANUSCRIPT_PATH: philippe_rigovanov # exclude the '.tex' / '.pdf' extension!
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: .
          root_file: |
            philippe_rigovanov.tex
      - name: Push PDFs
        run: |
          git add -f philippe_rigovanov.pdf
          git -c user.name='a1ip' -c user.email='phil@rigovanov.ru' commit -m "autoupdate PDFs"
          git push -q -f https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} ${GITHUB_REF##*/}
